/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UserRegistration;

import java.util.regex.Pattern;

public class UserRegistration {
	public boolean validateName(String name) {
		Pattern pattern;
		pattern = Pattern.compile("^[A-Z][a-z]{2,}");
		return pattern.matcher(name).matches();
	}
	
	public boolean validateEmail(String email) {
		Pattern pattern = Pattern.compile("abc(\\.xyz)?@bl\\.co(\\.in)?");
		return pattern.matcher(email).matches();
	}
	
	public boolean validatePhone(String phone) {
		Pattern pattern = Pattern.compile("^\\d{1,2}\\s\\d{10}$");
		return pattern.matcher(phone).matches();
	}
	
	public static boolean validatePassword(String password) {
		Pattern pattern = Pattern.compile(".{7,}");
		if(!pattern.matcher(password).matches()) {
			return false;
		}
		
		pattern = Pattern.compile(".*[A-Z].*");
		if (!pattern.matcher(password).matches()) {
			return false;
		}
		
		pattern = Pattern.compile(".*\\d.*");
		if (!pattern.matcher(password).matches()) {
			return false;
		}

		return true;
	}
}
