/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UserRegistration;

import java.util.regex.Pattern;

public class UserRegistration {
	public boolean validateName(String name) {
		Pattern pattern;
		pattern = Pattern.compile("^[A-Z][a-z]{2,}");
		return pattern.matcher(name).matches();
	}
	
	public boolean validateEmail(String email) {
		Pattern pattern = Pattern.compile("abc(\\.xyz)?@bl\\.co(\\.in)?");
		return pattern.matcher(email).matches();
	}
	
	public boolean validatePhone(String phone) {
		Pattern pattern = Pattern.compile("^\\d{1,2}\\s\\d{10}$");
		return pattern.matcher(phone).matches();
	}
}
